name: Data Integration Workflow

on:
  # Trigger the workflow manually for testing purposes
  workflow_dispatch:

  # Trigger the workflow on push or pull request to specific paths
  push:
    paths:
      - 'data-hub/**'
      - 'Script/**'

  pull_request:
    paths:
      - 'data-hub/**'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install ShellCheck
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Step 3: Run ShellCheck on scripts
      - name: Run Linter
        run: shellcheck Script/*.sh

  monitor_changes:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting passes before monitoring changes
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Monitor folder changes using dorny/paths-filter
      - name: Monitor Folders for Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            data:
              - 'data-hub/**'
              - 'db/**'

      # Step 3: Print which folders were changed
      - name: Print Changed Folders
        run: |
          echo "Data folder changed: ${{ steps.changes.outputs.data }}"

  data_integration:
    runs-on: ubuntu-latest
    needs: [monitor_changes]
    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Make the Bash script executable
      - name: Make Script Executable
        run: chmod +x Script/Data_integration.sh

      # Step 3: Run the Bash script
      - name: Run Data Integration Script
        run: ./Script/Data_integration.sh

      # Step 4: Check the updated dataset
      - name: Check the updated dataset
        run: wc -l db/data.csv

      # Step 5: Stage and Commit Report
      - name: Stage and Commit Report
        run: |
          git config --global user.name "Akp002"
          git config --global user.email "oborakpevwe123@gmail.com"
          git add db/data.csv
          git commit -m "Automated Integration Script"

      # Step 6: Push Changes
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
